Cyber/Skate_blog/skate_blog/main/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    #path('post/<int:id>/', views.detalle_post, name='detalle_post'),
    path('about_us/', views.about_us, name = "about_us"),
    path('subscribe/', views.subscribe, name='subscribe'),
    path('register/', views.register, name='register'),
    path("logout/", views.logout_view, name="logout"),
    path('search/', views.post_search, name='post_search'),
    #path('publicaciones/', views.listar_publicaciones, name='listar_publicaciones'),
    path('publicacion/<int:publicacion_id>/', views.ver_publicacion, name='ver_publicacion'),
    # Define una URL para el popup de comentarios
    path('agregar_comentario/<int:publicacion_id>/', views.agregar_comentario, name='agregar_comentario'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('register/politics/', views.politics, name='politics'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Cyber/Skate_blog/skate_blog/skate_blog/urls.py
# skate_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls')),
    path("", RedirectView.as_view(url="main/", permanent=True)),
    # path('accounts/', include('allauth.urls')),   # google allauth
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Cyber/Skate_blog/skate_blog/main/models.py
# main/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin, User
from django.db import models
from django.conf import settings
from ckeditor.fields import RichTextField
from django.urls import reverse

class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **kwargs):
        user = self.model(email=email, **kwargs)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password=None, **kwargs):
        user = self.model(email=email, is_staff=True,
                          is_superuser=True, **kwargs)
        user.set_password(password)
        user.save()
        return user
    

class CustomUserSB(AbstractBaseUser, PermissionsMixin):

    username = models.CharField(max_length=20, unique=True)
    email = models.EmailField(max_length=254, unique=True, default=None)
    
    genero = models.CharField(max_length=10, choices=[(
        'm', 'Masculino'), ('f', 'Femenino'), ('o', 'Otro')], blank=True)
    
    
    profile_image = models.ImageField(upload_to='profile_images/', blank=True, null=True)
    about_me = models.TextField(blank=True)
    accept_politics = models.BooleanField(default=False)
            
    direccion = models.CharField(max_length=100, blank=True)
    ciudad = models.CharField(max_length=50, blank=True)
    codigo_postal = models.CharField(max_length=10, blank=True)
    pais = models.CharField(max_length=50, blank=True)
    
    suscripcion = models.BooleanField(default=False)
    
    tarjeta_de_credito = models.CharField(max_length=20, blank=True)
    dni = models.CharField(max_length=20, blank=True)
    fecha_de_nacimiento = models.DateField(null=True, blank=True)

    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

class Post(models.Model):
    titulo = models.CharField(max_length=200)
    contenido = RichTextField(null=True,default=None)
    descripcion = models.CharField(max_length=250,null=True,default=None)
    imagen = models.ImageField(upload_to='images/', null=True, blank=True)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    suscripcion = models.BooleanField(default=False)


    def __str__(self):
        return self.titulo
    
    def get_absolute_url(self):
        """Returns the URL to access a detail record for this book."""
        return reverse('ver_publicacion', args=[str(self.id)])
    
class Comentarios(models.Model):
    Publicacion = models.ForeignKey(Post, on_delete=models.CASCADE)
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    texto = models.CharField(max_length=255)

    def __str__(self):
        return self.texto
    

Cyber/Skate_blog/skate_blog/main/views.py
# main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import  logout
from .models import Post,Comentarios,CustomUserSB
from .forms import RegisterForm, SubscriberForm,PostSearchForm
from django.db import IntegrityError
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import EditProfileForm

@login_required
def edit_profile(request):
    user = request.user
    if request.method == 'POST':
        form = EditProfileForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return redirect('profile')  # Redirect to the user's profile page
    else:
        form = EditProfileForm(instance=user)
    return render(request, 'edit_profile.html', {'form': form})

def register(request):
    form = RegisterForm()
    message = ""

    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            try:
                user = CustomUserSB()
                user.username = form.cleaned_data["username"]
                user.email = form.cleaned_data["email"]
                user.first_name = form.cleaned_data["first_name"]
                user.last_name = form.cleaned_data["last_name"]
                user.set_password(form.cleaned_data["password1"])

                if not form.cleaned_data["address"]:
                    user.direccion = None
                else:
                    user.direccion = form.cleaned_data["address"]

                user.pais = form.cleaned_data["country"]
                user.codigo_postal = form.cleaned_data["cp"]
                user.ciudad = form.cleaned_data["city"]
                user.genero = form.cleaned_data["genre"]

                user.profile_image = form.cleaned_data["profile_image"]
                user.about_me = form.cleaned_data["about_me"]

                """ if not form.cleaned_data["accept_politics"]:
                    user.accept_politics = False
                else:
                    user.accept_politics = True """

                user.is_active = True
                user.save()

                form = RegisterForm()
                messages.success(
                    request, "La operación se ha realizado con éxito.")

                # Redirige a la vista de inicio de sesión
                return redirect("login")

            except IntegrityError as e:
                message = "Error, username or email already exists"
            except Exception as e:
                message = str(e)
        else:
            message = "Error, formulario no válido"

    context = {
        "form": form,
        "message": message
    }

    return render(request, "registration/register.html", context=context)

@login_required
def subscribe(request):
    form = SubscriberForm()
    message = ""
    if request.method == "POST":
        form = SubscriberForm(request.POST)
        if form.is_valid():
            try:
                user = request.user
                if user.suscripcion == True:
                    message = "La cuenta ya está suscrita"
                else:
                    user.tarjeta_de_credito = form.cleaned_data["tarjeta_de_credito"]
                    user.dni = form.cleaned_data["dni"]

                    user.suscripcion = True
                    user.save()

                    form = SubscriberForm() 
                    messages.success(
                        request, "La operación se ha realizado con éxito.")

                    return redirect('index')

            except IntegrityError as e:
                message = "Error, username or email already exists"
            except Exception as e:
                message = str(e)
        else:
            message = "Error, formulario no válido"

    context = {
        "form": form,
        "message": message
    }

    return render(request, "registration/subscribe.html", context=context)

def index(request):
    premium_posts = Post.objects.filter(suscripcion=True)[:4]  # Obtener los primeros 4 posts premium
    non_premium_posts = Post.objects.filter(suscripcion=False)[:4]  # Obtener los primeros 4 posts no premium
    
    context = {
        'premium_posts': premium_posts,
        'non_premium_posts': non_premium_posts
    }  # Concatenar las dos listas de posts
    
    return render(request, 'index.html', context=context)

def about_us(request):
    return render(request, 'about_us.html')

@login_required
def profile(request):
    return render(request, 'profile.html')

@login_required
def logout_view(request):
    logout(request)
    return redirect('index')

""" def listar_publicaciones(request):
    user = request.user
    if user.suscripcion:
        publicaciones = Post.objects.all()
    else:
        publicaciones=Post.objects.filter(suscripcion= False)
    
    return render(request, 'listar_publicaciones.html', {'publicaciones': publicaciones}) """

@login_required
def ver_publicacion(request, publicacion_id):
    publicacion = get_object_or_404(Post, pk=publicacion_id)
    comentarios = Comentarios.objects.filter(Publicacion=publicacion)
    if not request.user.suscripcion:
            return redirect('subscribe')
    
    return render(request, 'ver_publicacion.html', {'publicacion': publicacion, 'comentarios': comentarios})

@login_required
def agregar_comentario(request, publicacion_id):
    if request.method == 'POST':
        texto = request.POST['texto']
        publicacion = get_object_or_404(Post, pk=publicacion_id)  # Verifica si la publicación existe
        usuario = request.user
        comentario = Comentarios(Publicacion=publicacion, usuario=usuario, texto=texto)  # Asegúrate de que los nombres de los campos sean correctos
        comentario.save()
    return redirect('ver_publicacion', publicacion_id=publicacion_id)

@login_required
def post_search(request):
    if request.method == 'GET':
        form = PostSearchForm(request.GET)
        if form.is_valid():  # Check if the form is valid before accessing cleaned_data
            query = form.cleaned_data.get('query')
            # Apply filtering based on user input (query) and other criteria
            if query:
                posts = Post.objects.filter(titulo__icontains=query)
            else:
                posts = Post.objects.all()
        else:
            # Handle the case when the form is not valid
            posts = Post.objects.all()  # You can provide a default queryset here
    else:
        form = PostSearchForm()
        user = request.user

        if user.suscripcion:
            posts = Post.objects.all()
        else:
            posts=Post.objects.filter(suscripcion= False)

        

    return render(request, 'posts.html', {'form': form, 'posts': posts})

def politics(request):
    return render(request, 'politica_privacidad.html')

Cyber/Skate_blog/skate_blog/main/templates/about_us.html
{% extends "base.html" %}
{% block title %} Skate Blog {% endblock %}
{% block content %}

    <!-- Menu -->
    <header id="header" class="alt">
        <div class="logo"><a href="{% url 'index' %}">Skate blog <span></span></a></div>
        <a href="#menu">Menu</a>
    </header>

    <!-- Header-->
    <section id="two" class="wrapper style3">
        <div class="inner">
            <header class="align-center">
                <p>About us</p>
                <h2>The best place for skaters</h2>
            </header>
        </div>
    </section>

    <!-- About us -->
    <section id="three" class="wrapper style2">
        <div class="inner">
            <div class="box">
                <div class="content">
                    <header class="align-center">
                        <p><b>Welcome to [Skate blog], the hub for skaters by skaters</b></p><br>
                        <h3>Who we are</h3>
                    </header>
                    <p>We are a group of passionate skateboarders who live and breathe the skateboarding lifestyle. At [Skate], we know the thrill of cruising down the streets, the satisfaction of landing a new trick, and the sense of community that comes with being a skater. We created this platform to share our love for skateboarding with others who feel the same way.</p>
                    <header class="align-center">
                        <h3>What We Do</h3>
                    </header>
                    <p>At [Skate blog], we bring you the most exciting, up-to-date content from the world of skateboarding:</p>

                    <p><b>Skater Posts:</b> Get to know your fellow skaters! We feature posts from skaters of all levels and styles, sharing their stories, experiences, and favorite tricks. Whether you’re a seasoned pro or a newbie, there’s something for everyone to enjoy and learn.</p>
                        
                    <p><b>Competition News:</b> Stay informed about the latest skateboarding competitions around the world. From local contests to international championships, we've got you covered with updates, results, and behind-the-scenes insights.</p>
                        
                    <p><b>Skate Spots:</b> Discover the best spots to skate, both locally and globally. Our team and community members contribute insights about the coolest skate parks, street spots, and hidden gems where you can unleash your skills and creativity.</p>
                    
                    <header class="align-center">
                        <h3>Join Our Community</h3>
                    </header>
                    <p>Vivamus ultricies mollis mauris quis molestie. Quisque eu mi velit. In et cursus nibh. Donec facilisis, orci sed mollis hendrerit, nunc risus mattis odio, eget efficitur nisl orci a lectus. Aenean finibus neque convallis orci sollicitudin tincidunt. Vivamus lacinia facilisis diam, quis facilisis nisi luctus nec. Aliquam ac molestie enim, ut ultrices elit. Fusce laoreet vulputate risus in tincidunt. Sed commodo mollis maximus. Nullam varius laoreet nibh sit amet facilisis. Donec ac odio vehicula, consequat elit et, sodales justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nullam ac auctor mauris, in hendrerit libero. </p>
                </div>
            </div>
        </div>
    </section>

    <!-- Ending -->
    <section id="four" class="wrapper style3">
        <div class="inner">
            <header class="align-center">
                <p></p>
                <h2>Happy skating, and welcome to the [Skate blog] family!</h2>
            </header>
        </div>
    </section>

    <!-- Footer -->
	<footer id="footer" style="background-color: #ffc107;">
		<div class="container">
		  <ul class="icons">
			<li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
			<li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
			<li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
			<li><a href="#" class="icon fa-envelope-o"><span class="label">Email</span></a></li>
		  </ul>
		</div>
    </footer>
    
{% endblock %}  

Cyber/Skate_blog/skate_blog/main/templates/base.html
	<!-- base.html -->
	{% load static %}
	<!DOCTYPE HTML>
	<html>
		<head>
			<title>{% block title %}Skate blog{% endblock %}</title>
			<meta charset="utf-8">
			<meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1">
			<meta name="viewport" content="width=device-width, initial-scale=1">
			<!-- Google Fonts -->
			<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,900&display=swap" rel="stylesheet">
			<!-- Bootstrap CSS -->
			<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css'>
			<!-- Font Awesome CSS -->
			<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css'>

			<link rel="stylesheet" href="{% static 'css/base.css' %}">
			<link rel="icon" type="image/png" href="{% static "images/posts/logo_skateblog2.png" %}"sizes="48x48">
			<!-- Boostrap -->
			<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
			{% block extra_styles %}{% endblock %}
		</head>
		<body>
		<!-- Nav -->
	<nav id="menu">
		<ul class="links">
			<li><a href="{% url 'index' %}">Home</a></li>
			<li><a href="{% url 'post_search' %}">Post</a></li>
			<li><a href="{% url 'about_us' %}">About us</a></li>
			<li><a href="{% url 'profile' %}">Profile</a></li>
			
			{% if user.is_authenticated %}
			<li><a href="{% url 'logout' %}?next=/" class="btn btn-warning">Logout <i class="fas fa-sign-out-alt"></i></a></li>
			{% else %}
			<li><a href="{% url "login" %}">Register / Login</a></li>
		</ul>
		{% endif %}
	</nav>

			{% block content %}
			{% endblock %}


				<!-- Scripts -->
				<script src="{% static 'js/jquery.min.js' %}"></script>
				<script src="{% static 'js/jquery.scrollex.min.js' %}"></script>
				<script src="{% static 'js/skel.min.js' %}"></script>
				<script src="{% static 'js/util.js' %}"></script>
				<script src="{% static 'js/main.js' %}"></script>

				<!-- Boostrap -->
				<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
				<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
				<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
		</body>
	</html>

Cyber/Skate_blog/skate_blog/main/templates/comentar_publicacion.html
<!-- comentar_publicacion.html -->

{% block content %}
  <h2>Comentar la publicación "{{ publicacion.titulo }}"</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Comentar</button>
  </form>
  <a href="{% url 'ver_publicacion' publicacion.id %}">Volver a la publicación</a>

{% endblock %}

Cyber/Skate_blog/skate_blog/main/templates/detalle_post.html
<!-- templates/main/detalle_post.html -->
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
{% endblock %}

{% block content %}
    <h1>{{ post.titulo }}</h1>
    <p>{{ post.contenido }}</p>

    <div class="{% if not usuario_logeado %}overlay{% endif %}">
            <img src="{{ post.imagen.url }}" alt="{{ post.titulo }}" class="{% if not usuario_logeado %}greyed-out{% endif %}">
    </div>

    {% if not usuario_logeado %}
        <div class="overlay-text">Necesitas estar registrado para ver el contenido completo.</div>
    {% endif %}

{% endblock %}

Cyber/Skate_blog/skate_blog/main/templates/edit_profile.html
<!-- main/templates/edit_profile.html -->
{% extends "base.html" %}
{% block title %} Edit Profile {% endblock %}
{% block content %}
{% load static %}


<!-- Menu -->
<header id="header" class="alt">
    <div class="logo">
        <a href="{% url 'index' %}">
            <img style="width: 40px; height: 40px;" src="{% static "images/posts/logo_skateblog.png" %}">
            <span></span>
        </a>
    </div>
    <a href="#menu">Menu</a>
</header>

  <!-- Header-->
  <section id="two" class="wrapper style3">
    <div class="inner">
        <header class="align-center">
            <p>Edit Profile</p>
        </header>
    </div>
</section>

<div class="container">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save Changes</button>
    </form>
</div>

    <!-- Footer -->
    <footer id="footer" style="background-color: #ffc107;">
        <div class="container">
        <ul class="icons">
            <li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
            <li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
            <li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
            <li><a href="#" class="icon fa-envelope-o"><span class="label">Email</span></a></li>
        </ul>
        </div>
    </footer>

{% endblock %}

Cyber/Skate_blog/skate_blog/main/templates/listar_publicaciones.html
{% block content %}
  <h1>Lista de Publicaciones</h1>
  <ul>
    {% for publicacion in publicaciones %}
      <li>
        <h2 href="{% url 'ver_publicacion' publicacion.id %}" >{{ publicacion.titulo }}</h2>
            {{ publicacion.contenido | safe }}
                
                <!-- Mostrar imagen -->
          <img src="{{ publicacion.imagen.url }}" decoding="auto" width="750em" height="750em"></img>
      </li>
    {% endfor %}
  </ul>

  
{% endblock %}

Cyber/Skate_blog/skate_blog/main/templates/politica_privacidad.html
{% extends "base.html" %}
{% block title %} Skate Blog {% endblock %}
{% block content %}

    <!-- Menu -->
    <header id="header" class="alt">
        <div class="logo"><a href="{% url 'index' %}">Skate blog <span></span></a></div>
        <a href="#menu">Menu</a>
    </header>

    <!-- Header-->
    <section id="two" class="wrapper style3">
        <div class="inner">
            <header class="align-center">
                <p>Privacy Policy</p>
                <h2>The best place for skaters</h2>
            </header>
        </div>
    </section>

    <!-- Política de Privacidad en Inglés -->
    <section id="three" class="wrapper style2">
        <div class="inner">
            <div class="box">
                <div class="content">
                    <p><b>Privacy Policy</b></p>
                    <p>Effective Date: 02/10/2023</p>

                    <p><b>1. General Information</b></p>
                    <p>1.1. Blog Skate (hereinafter referred to as "We" or "Our") is the data controller for the personal data of users of this website.</p>
                    <p>1.2. Our contact address is Paseo de la Castellana 89, and our contact email is hello@immune.institute.</p>

                    <p><b>2. Collection of Personal Data</b></p>
                    <p>2.1. We collect personal data when users register on our website, complete forms, interact with our services, or provide us with information in other ways.</p>
                    <p>2.2. The types of personal data we may collect include, among others:</p>
                    <ul>
                        <li>Contact information (name, email address, phone number).</li>
                        <li>Registration information (username, password).</li>
                        <li>Payment information (if applicable, e.g., for billing monthly subscription fees).</li>
                    </ul>
                    
                    <p><b>3. Use of Personal Data</b></p>
                    <p>3.1. We use personal data for the following purposes:</p>
                    <ul>
                        <li>Processing subscriber registrations.</li>
                        <li>Providing access to exclusive content.</li>
                        <li>Allowing user interaction in the forum and comments.</li>
                        <li>Billing monthly fees (if applicable).</li>
                    </ul>
                    <p>3.2. We will not share personal data with third parties without the user's consent unless we are legally obligated to do so.</p>

                    <p><b>4. Data Security</b></p>
                    <p>4.1. We have implemented technical and organizational security measures to protect the personal data of our users against loss, unauthorized access, and other risks.</p>

                    <p><b>5. User Rights</b></p>
                    <p>5.1. Users have rights regarding their personal data, including the right to access, rectify, delete, object to processing, and request data portability. To exercise these rights, users can contact us at hello@immune.institute.</p>

                    <p><b>6. Changes to the Privacy Policy</b></p>
                    <p>6.1. We may update this Privacy Policy at any time. An updated version will be published on our website.</p>

                    <p><b>7. Contact</b></p>
                    <p>7.1. If users have any questions about this Privacy Policy or our data processing practices, they can contact us at hello@immune.institute.</p>
                </div>
            </div>
        </div>
    </section>

    <!-- Ending -->
    <section id="four" class="wrapper style3">
        <div class="inner">
            <header class="align-center">
                <p></p>
                <h2>Happy skating, and welcome to the [Skate blog] family!</h2>
            </header>
        </div>
    </section>

{% endblock %}

Cyber/Skate_blog/skate_blog/main/templates/profile.html
{% extends "base.html" %}
{% load static %}
{% block title %} Skate Blog {% endblock %}
{% block extra_styles %}
    <link rel="stylesheet" href="{% static 'css/specific/profile.css' %}">
{% endblock %}
{% block content %}

<!-- Menu -->
<header id="header" class="alt">
    <div class="logo">
        <a href="{% url 'index' %}">
            <img style="width: 40px; height: 40px;" src="{% static "images/posts/logo_skateblog.png" %}">
            <span></span>
        </a>
    </div>
    <a href="#menu">Menu</a>
</header>

<!-- Header-->
<section id="two" class="wrapper style3">
    <div class="inner">
        <header class="align-center">
            <h2>Profile</h2>
        </header>
    </div>
</section>

<!-- Your provided HTML content goes here -->
<section class = "profile_background">
<div class="student-profile py-4">
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <div class="card shadow-sm">
                    <div class="card-header bg-transparent text-center">
                        <img class="profile_img" src="{% if user.profile_image %}{{ user.profile_image.url }}{% else %}{% static 'images/profile/no_photo.jpg' %}{% endif %}" alt="{{ user.username }}'s profile picture">
                        <h3>{{ user.username }}</h3>
                        <button class="edit-profile-button" onclick="window.location.href='{% url 'edit_profile' %}'">Edit Profile</button>
                    </div>
                    <div class="card-body">
                        <p class="mb-0"><strong class="pr-1">Username:</strong>{{ user.username }}</p>
                        <p class="mb-0"><strong class="pr-1">Gender:</strong>{{ user.get_genero_display }}</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-8">
                <div class="card shadow-sm">    
                    <div class="card-header bg-transparent border-0">
                        <h3 class="mb-0"><i class="far fa-clone pr-1"></i>General Information</h3>
                    </div>
                    <div class="card-body pt-0">
                        <table class="table table-bordered">
                            <tr>
                                <th width="30%">Direccion</th>
                                <td width="2%">:</td>
                                <td>{{ user.direccion }}</td>
                            </tr>
                            <tr>
                                <th width="30%">City</th>
                                <td width="2%">:</td>
                                <td>{{ user.ciudad }}</td>
                            </tr>
                            <tr>
                                <th width="30%">Country</th>
                                <td width="2%">:</td>
                                <td>{{ user.pais }}</td>
                            </tr>
                            <tr>
                                <th width="30%">Email</th>
                                <td width="2%">:</td>
                                <td>{{ user.email }}</td>
                            </tr>
                        </table>
                    </div>
                </div>
                <div style="height: 26px"></div>
                <div class="card shadow-sm">
                    <div class="card-header bg-transparent border-0">
                        <h3 class="mb-0"><i class="far fa-clone pr-1"></i>About Me</h3>
                    </div>
                    <div class="card-body pt-0">
                        <p>{{ user.about_me }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</section>
{% endblock %}

Cyber/Skate_blog/skate_blog/main/templates/ver_publicacion.html
{% extends "base.html" %}
{% load static %}
{% block title %} Skate Blog {% endblock %}
{% block extra_styles %}
    <link rel="stylesheet" href="{% static 'css/specific/ver_post.css' %}">

{% endblock %}
{% block content %}
{% load static %}

<header id="header" class="alt">
  <div class="logo"><a href="{% url 'index' %}">Skate blog <span></span></a></div>
  <a href="#menu">Menu</a>
</header>

<!-- Header-->
<section id="two" class="wrapper style3">
  <div class="inner">
      <header class="align-center">
          <p>Blog</p>
          <h1>{{ publicacion.titulo }}</h1>
      </header>
  </div>
</section>

<div id="content-container">
  {% if publicacion.imagen %}
  <img src="{{ publicacion.imagen.url }}" class="card-img-top" alt="{{ publicacion.titulo }}">
  {% endif %}
  <div class="card_content">
    <p  >{{ publicacion.contenido | safe }}</p>
  </div>
    <h2>Comentarios</h2>
    <ul id="comments">
      {% for comentario in comentarios %}
        <li class="comment">
            <img class="profile-image" src="{% static 'images/profile-placeholder.png' %}" alt="User Profile">
            <div>
                <span class="user">{{ comentario.usuario }}:</span> {{ comentario.texto }}
            </div>
        </li>
      {% endfor %}
    </ul>

    <h3>Agregar Comentario</h3>
    <form id="add-comment" method="post" action="{% url 'agregar_comentario' publicacion.id %}">
      {% csrf_token %}
      <textarea name="texto" placeholder="Escribe tu comentario aquí"></textarea>
      <input type="submit" value="Comentar">
    </form>
</div>

<footer id="footer">
  <div class="container">
    <ul class="icons">
      <li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
      <li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
      <li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
      <li><a href="#" class="icon fa-envelope-o"><span class="label">Email</span></a></li>
    </ul>
  </div>
        
  <div class="copyright">
    <img style="width: 100px; height: 100px;" src="{% static 'images/posts/logo_skateblog.png' %}">
  </div>
</footer>
{% endblock %}